stages:
  - setup
  - test
  - report

variables:
  VENV_DIR: venv
  ALLURE_RESULTS_DIR: reports/allure-results

before_script:
  - apt-get update && apt-get install -y python3-venv python3-pip
  - python3 -m venv $VENV_DIR
  - source $VENV_DIR/bin/activate
  - pip install -r requirements.txt

setup-environment:
  stage: setup
  script:
    - echo "✅ Environment setup completed"

run-behave-tests:
  stage: test
  script:
    - source $VENV_DIR/bin/activate
    - behave -f allure_behave.formatter:AllureFormatter -o $ALLURE_RESULTS_DIR
  artifacts:
    paths:
      - $ALLURE_RESULTS_DIR
    expire_in: 7 days

generate-allure-report:
  stage: report
  image:
    name: Diwakar/allure-docker-service
    entrypoint: [""]
  script:
    - mkdir -p public
    - allure generate $ALLURE_RESULTS_DIR -o public --clean
  artifacts:
    paths:
      - public
  only:
    - main
