name: Run Behave Tests

on:
  push:
    branches:
      - Reporting
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Behave Tests
        run: behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results

      - name: Install Allure Commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.23.0.tgz
          tar -zxvf allure-2.23.0.tgz
          sudo mv allure-2.23.0 /opt/allure
          echo "export PATH=\$PATH:/opt/allure/bin" >> ~/.bashrc
          source ~/.bashrc
          echo "Allure Installed Successfully!"

      - name: Generate Allure HTML Report
        run: |
          /opt/allure/bin/allure generate reports/allure-results -o reports/allure-report --clean

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-html-report
          path: reports/allure-report
